### ISSUE TITLE
Fix crash on heroku

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/vaccimailer#1]
It works fine for development environment, but when hosted on heroku, crashes everytime

**Comment by parthlaw** [comment]
Provide an image of heroku logs..

**Comment by TheNinza** [comment]
![WhatsApp Image 2021-05-11 at 1 42 16 AM](https://user-images.githubusercontent.com/62726436/117721597-afd8df00-b1fd-11eb-9d53-2a949cbed20d.jpeg)

**Comment by saswatamcode** [comment]
Seems like the API call fails here due to some config issue...but also Heroku forcefully makes free dynos sleep. So running a job like this won't exactly work since this is taken to be of job type `web` by default as shown by the logs. You can read more about this [here](https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes)!

Also instead of using [timeout](https://github.com/TheNinza/vaccimailer/blob/main/index.js#L84) using something like node-cron might work better!
